trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
  
- task: Docker@2
  inputs:
    containerRegistry: '$(AzureCRConnection)'
    repository: 'abcrepo'
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Docker image build'

- task: Docker@2
  inputs:
    containerRegistry: '$(AzureCRConnection)'
    repository: 'abcrepo'
    command: 'push'
  displayName: 'Docker image push'